### PR TITLE
Workflow for Docker Images

### PR DESCRIPTION
**Pull request by jollySleeper**
This pull request automates the creation of Docker images for arm64 and amd64 builds on each new version.

### CODE REVIEW

**Comment by zyachel** [comment]
can you mention important env variables to run the built image? because it won't run successfully without them

something like this:

```bash
docker run -d \
  --name libremdb \
  -p 3000:3000 \
  -e NEXT_PUBLIC_URL=https://iket.me \
  -e AXIOS_USERAGENT="Mozilla/5.0 (X11; Linux x86_64; rv:108.0) Gecko/20100101 Firefox/130.0" \
  -e AXIOS_ACCEPT="text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8" \
  ghcr.io/zyachel/libremdb:latest #replace NEXT_PUBLIC_URL with your own
```

**Comment by jollySleeper** [comment]
> can you mention important env variables to run the built image? because it won't run successfully without them
> 
> something like this:
> 
> ```shell
> docker run -d \
>   --name libremdb \
>   -p 3000:3000 \
>   -e NEXT_PUBLIC_URL=https://iket.me \
>   -e AXIOS_USERAGENT="Mozilla/5.0 (X11; Linux x86_64; rv:108.0) Gecko/20100101 Firefox/130.0" \
>   -e AXIOS_ACCEPT="text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8" \
>   ghcr.io/zyachel/libremdb:latest #replace NEXT_PUBLIC_URL with your own
> ```

Yu suggesting me to add this to README.md right?

**Comment by zyachel** [comment]
yes

**Comment by jollySleeper** [comment]
@zyachel Please take a look now.

**Pull request merged**
