### PR TITLE
Anonymous media proxy, local docker, private IP ratelimit and caching with redis

### PR DESCRIPTION
**Pull request by httpjamesm**
This PR adds numerous features, most notably with anonymous media proxying.

Previously, libremdb would contact Amazon servers directly to serve some images and videos (those that aren't proxied via Next), but this update adds a new `/api/media_proxy` endpoint that relays eligible content from Amazon to the user in an anonymous fashion. All Amazon sees is the instance contacting them for assets, not the user.

Docs and FAQ have been updated.

### CODE REVIEW

**Comment by zyachel** [comment]
I'll test this locally first before merging.

**Comment by zyachel** [comment]
@httpjamesm, the cached responses aren't working locally for some reason. I get 302 as network response for proxied requests, but there's no content.  

also, can't we just do this(in media_proxy.ts):  
```ts
import { NextApiRequest, NextApiResponse } from 'next';
import axiosInstance from '../../utils/axiosInstance';

export default async function handler(
  req: NextApiRequest,
  res: NextApiResponse
) {
  try {
    const mediaUrl = req.query.url as string;

    if (!mediaUrl)
      return res.status(400).json({
        success: false,
        message: 'Missing query',
      });

    const mediaRes = await axiosInstance.get(mediaUrl, {
      responseType: 'stream',
    });

    res.setHeader('Content-Type', mediaRes.headers['content-type']);
    mediaRes.data.pipe(res);
  } catch (e) {
    console.log(e);
  }
}

export const config = {
  api: {
    responseLimit: false,
  },
};

```

granted, we'll hit IMDb's servers on every request, but we're doing it anyway to get data.

**Comment by httpjamesm** [comment]
Sure, you could do that, but the cache would be a lot faster, especially for large media like images and video. 

Are you sure Redis is running and configured properly? I suggest running the docker compose file.

**Comment by zyachel** [comment]
I managed to make it work. when getting media from redis, I used `getBuffer` instead of `get`.

Here's the updated code:
```ts
import { NextApiRequest, NextApiResponse } from 'next'
import redis from '../../utils/redis'
import axiosInstance from '../../utils/axiosInstance'
import { AxiosResponse } from 'axios'

const regex =
  /^https:\/\/((m\.)?media-amazon\.com|imdb-video\.media-imdb\.com).*\.(jpg|jpeg|png|mp4|gif|webp).*$/

export default async function handler(
  req: NextApiRequest,
  res: NextApiResponse
) {
  const mediaUrl = req.query.url as string | undefined

  if (!mediaUrl || !regex.test(mediaUrl))
    return res.status(400).json({
      success: false,
      message: 'Invalid query',
    })

  const cachedMedia = await redis.getBuffer(mediaUrl)

  if (cachedMedia) {
    res.setHeader('x-cached', 'true')
    res.status(302).send(cachedMedia)
    return
  }

  let mediaRes: AxiosResponse
  try {
    mediaRes = await axiosInstance(mediaUrl, { responseType: 'arraybuffer' })
  } catch {
    res.status(404)
    res.json({
      success: false,
      message: 'Error from IMDb',
    })
    return
  }

  const data = mediaRes.data
  // save in redis for 30 minutes
  await redis.setex(mediaUrl, 30 * 60, Buffer.from(data))

  // send media
  res.setHeader('x-cached', 'false')
  res.send(data)
}

export const config = {
  api: {
    responseLimit: false,
  },
}
```

As a side note, I think using redis should be optional(could be enabled by a .env variable). If it is disabled, we can then just pipe the stream we get from  imdb.

**Comment by httpjamesm** [comment]
Done, I've made redis optional.

**Pull request merged**
